basePath: /internal/v1
definitions:
  action_log.Request:
    properties:
      cid:
        example: 1293257
        type: integer
      entry:
        example: Changed Preferred OIs to RP
        type: string
    required:
    - cid
    - entry
    type: object
  action_log.Response:
    properties:
      cid:
        example: 1293257
        type: integer
      created_at:
        example: "2021-01-01T00:00:00Z"
        type: string
      created_by:
        example: '''1234567'' or ''System'''
        type: string
      entry:
        example: Changed Preferred OIs to RP
        type: string
      id:
        example: 1
        type: integer
      updated_at:
        example: "2021-01-01T00:00:00Z"
        type: string
      updated_by:
        example: '''1234567'' or ''System'''
        type: string
    type: object
  utils.ErrResponse:
    properties:
      code:
        description: application-specific error code
        type: integer
      error:
        description: application-level error message, for debugging
        type: string
      status:
        description: user-level status message
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: vatusa6@vatusa.net
    name: VATUSA Support
    url: http://www.swagger.io/support
  description: VATUSAs internal API for use by other internal VATUSA services.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: VATUSA Internal
  version: "0.1"
paths:
  /action_log:
    get:
      consumes:
      - application/json
      description: List all action log entries
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/action_log.Response'
            type: array
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: List all action log entries
      tags:
      - action_log
    post:
      consumes:
      - application/json
      description: Create a new action log entry
      parameters:
      - description: Action Log Entry
        in: body
        name: action_log
        required: true
        schema:
          $ref: '#/definitions/action_log.Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/action_log.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Create a new action log entry
      tags:
      - action_log
  /action_log/{id}:
    get:
      consumes:
      - application/json
      description: Get an action log entry
      parameters:
      - description: Action Log Entry ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/action_log.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ErrResponse'
      summary: Get an action log entry
      tags:
      - action_log
swagger: "2.0"
